name: Terraform Quality

on:
    push:
        branches:
            - main
        paths:
            - 'actions-arc-dind-chart'
            - 'actions-arc-k8s-chart'
            - 'actions-ebs-chart'
            - 'aws'
            - 'kind'
            - 'minikube'

jobs:
    check-terraform-format:
        runs-on: arc-runners
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              uses: ./.github/workflows/dependencies
              with:
                runner: ${{ runner.os }}
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform fmt
              run: terraform fmt -check
