name: Terraform Quality

on:
    pull_request:
        branches:
            - main
jobs:
  terraform-check:
    runs-on: arc-runners
    permissions:    
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/dependencies
        with:
          runner: ${{ runner.os }}
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Format Terraform Config
        run: cd /home/runner/_work/terraform-gha/terraform-gha && terraform fmt -check
      # - name: Validate Terraform Config
      #   uses: terraform validate 
      # - name: Plan Terraform Config
      #   run:  make plan-kind-dind && make plan-kind-k8s && make plan-minikube-dind && make plan-minikube-k8s
          